Homework 2
================
2025-09-30

Loading the library first:

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.2
    ## ✔ ggplot2   3.5.2     ✔ tibble    3.3.0
    ## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
    ## ✔ purrr     1.1.0     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(lubridate)
```

Getting the exact path:

``` r
getwd()
```

    ## [1] "/Users/karolinawiesiolek/Desktop/Data_Science/Homeworks/Homework2/Homework2_kw3041"

Getting the data frames up on the R:

``` r
pols_month = 
  read_csv("/Users/karolinawiesiolek/Desktop/Data_Science/Homeworks/Homework2/data/pols-month.csv") 
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
unemployment = 
  read_csv("/Users/karolinawiesiolek/Desktop/Data_Science/Homeworks/Homework2/data/unemployment.csv") 
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
snp = 
  read_csv("/Users/karolinawiesiolek/Desktop/Data_Science/Homeworks/Homework2/data/snp.csv") 
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

## Working on pols_month – first part of Problem 1.

Step 1. Separate by year/month/day. Step 2. Replace month number with a
month name. Step 3. Create ‘president’ variable taking values gop and
dem. First, I used a second mutate to add new variable but that didn’t
work so i merged ‘mutate’. Step 4. Using `select` removed columns.

``` r
pols_month =
  read_csv("/Users/karolinawiesiolek/Desktop/Data_Science/Homeworks/Homework2/data/pols-month.csv")
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
  pols_month_clean = pols_month %>% 
  separate(mon, into = c("year", "month", "day"), sep = "-", convert = TRUE) %>% 
  mutate(
    month = month.name[month],
    president = case_when(
    prez_gop == 1 ~ "gop",
    prez_dem == 1 ~ "dem"
  )
) %>% 

select(-prez_dem, -prez_gop, -day) 
```

## 2nd part of Problem 1 – snp.csv

Step 1. Arrange according to year/month - these are first columns. Step
2. Lubridate package and then used it to oprganized with year and month
as the separate wasn’t working.

``` r
snp =
  read_csv("/Users/karolinawiesiolek/Desktop/Data_Science/Homeworks/Homework2/data/snp.csv")
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
  snp_clean <- snp %>%
  mutate(date = mdy(date),                
         year = year(date),
         month = month(date, label = TRUE, abbr = FALSE)) %>%  
  select(year, month, everything()) %>%
  arrange(year, match(as.character(month), month.name))

head(snp_clean)
```

    ## # A tibble: 6 × 4
    ##    year month    date       close
    ##   <dbl> <ord>    <date>     <dbl>
    ## 1  1969 January  1969-01-02 103. 
    ## 2  1969 February 1969-02-03  98.1
    ## 3  1969 March    1969-03-03 102. 
    ## 4  1969 April    1969-04-01 104. 
    ## 5  1969 May      1969-05-01 103. 
    ## 6  1969 June     1969-06-02  97.7

## Part 3 of Problem 1 – unemployment data.

``` r
unemployment_long = unemployment %>% 
  pivot_longer(
    cols = -Year,          
    names_to = "month",
    values_to = "unemployment_rate"
  ) %>% 
  rename(year = Year) %>%  
  mutate(
    month = case_when(
      month %in% c("1", "01", "Jan") ~ "January",
      month %in% c("2","02","Feb") ~ "February",
      month %in% c("3","03","Mar") ~ "March",
      month %in% c("4","04","Apr") ~ "April",
      month %in% c("5","05","May") ~ "May",
      month %in% c("6","06","Jun") ~ "June",
      month %in% c("7","07","Jul") ~ "July",
      month %in% c("8","08","Aug") ~ "August",
      month %in% c("9","09","Sep") ~ "September",
      month %in% c("10","Oct") ~ "October",
      month %in% c("11","Nov") ~ "November",
      month %in% c("12","Dec") ~ "December"
    )
  ) %>%
  arrange(year, match(month, month.name))

head(unemployment_long)
```

    ## # A tibble: 6 × 3
    ##    year month    unemployment_rate
    ##   <dbl> <chr>                <dbl>
    ## 1  1948 January                3.4
    ## 2  1948 February               3.8
    ## 3  1948 March                  4  
    ## 4  1948 April                  3.9
    ## 5  1948 May                    3.5
    ## 6  1948 June                   3.6

## Part 4 of Problem 1 – mergning.

``` r
combined_df = pols_month_clean %>%
  left_join(snp_clean, by = c("year", "month")) %>%
  left_join(unemployment_long, by = c("year", "month"))

glimpse(combined_df)
```

    ## Rows: 822
    ## Columns: 12
    ## $ year              <dbl> 1947, 1947, 1947, 1947, 1947, 1947, 1947, 1947, 1947…
    ## $ month             <chr> "January", "February", "March", "April", "May", "Jun…
    ## $ gov_gop           <dbl> 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 24, 24, 22, …
    ## $ sen_gop           <dbl> 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 53, …
    ## $ rep_gop           <dbl> 253, 253, 253, 253, 253, 253, 253, 253, 253, 253, 25…
    ## $ gov_dem           <dbl> 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 24, …
    ## $ sen_dem           <dbl> 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 48, …
    ## $ rep_dem           <dbl> 198, 198, 198, 198, 198, 198, 198, 198, 198, 198, 19…
    ## $ president         <chr> "dem", "dem", "dem", "dem", "dem", "dem", "dem", "de…
    ## $ date              <date> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
    ## $ close             <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
    ## $ unemployment_rate <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 3.4,…

The combined dataset merges U.S. politics, stock market, and
unemployment data. It spans 1947–2015, with 12 variables including party
counts in government, presidential affiliation, S&P 500 closing values,
unemployment rates, and time (year, month).

## Problem 2 part 1 with mr. Trash Wheel

``` r
library(readxl)
library(dplyr)
```

``` r
mr_trashwheel <- read_excel(
  "/Users/karolinawiesiolek/Desktop/Data_Science/Homeworks/Homework2/data/Trash_Wheel_Collection_Data.xlsx",
  sheet = "Mr. Trash Wheel"
) %>% 
  janitor::clean_names() %>% 
  filter(!is.na(dumpster)) %>% 
  mutate(
    sports_balls = as.integer(round(sports_balls)),
    trash_wheel = "Mr. Trash Wheel"
  ) %>% 
  select(dumpster, month, year, date, weight_tons, volume_cubic_yards,
         plastic_bottles, polystyrene, cigarette_butts, glass_bottles,
         plastic_bags, wrappers, sports_balls, homes_powered, trash_wheel)
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`

## Problem 2 - part 2 with next data set.

``` r
professor_trashwheel <- read_excel(
  "/Users/karolinawiesiolek/Desktop/Data_Science/Homeworks/Homework2/data/Trash_Wheel_Collection_Data.xlsx",
  sheet = "Professor Trash Wheel"
) %>% 
  janitor::clean_names() %>% 
  filter(!is.na(dumpster)) %>%
  mutate(
    weight_tons = as.integer(round(weight_tons)),
    trash_wheel = "Professor Trash Wheel"
  ) %>% 
  select(dumpster, month, year, date, weight_tons, volume_cubic_yards,
         plastic_bottles, polystyrene, cigarette_butts, glass_bottles,
         plastic_bags, wrappers, homes_powered)
```

## Problem 2 – Part 3

``` r
gwynnda = read_excel(
  "/Users/karolinawiesiolek/Desktop/Data_Science/Homeworks/Homework2/data/Trash_Wheel_Collection_Data.xlsx",
  sheet = "Gwynns Falls Trash Wheel",
) %>%
  janitor::clean_names() %>%
  filter(!is.na(dumpster)) %>%  
  mutate(
    weight_tons = as.integer(round(weight_tons)), 
    trash_wheel = "Gwynnda" 
  ) %>%
  select(dumpster, month, year, date, weight_tons, volume_cubic_yards,
         plastic_bottles, polystyrene, cigarette_butts,
         plastic_bags, wrappers, homes_powered)
```

Combining all the data:

``` r
mr_trashwheel <- mr_trashwheel %>% mutate(year = as.integer(year))
professor_trashwheel <- professor_trashwheel %>% mutate(year = as.integer(year))
gwynnda <- gwynnda %>% mutate(year = as.integer(year))

all_trashwheels <- bind_rows(
  mr_trashwheel,
  professor_trashwheel,
  gwynnda
)

glimpse(all_trashwheels)
```

    ## Rows: 1,188
    ## Columns: 15
    ## $ dumpster           <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, …
    ## $ month              <chr> "May", "May", "May", "May", "May", "May", "May", "M…
    ## $ year               <int> 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 201…
    ## $ date               <dttm> 2014-05-16, 2014-05-16, 2014-05-16, 2014-05-17, 20…
    ## $ weight_tons        <dbl> 4.31, 2.74, 3.45, 3.10, 4.06, 2.71, 1.91, 3.70, 2.5…
    ## $ volume_cubic_yards <dbl> 18, 13, 15, 15, 18, 13, 8, 16, 14, 18, 15, 19, 15, …
    ## $ plastic_bottles    <dbl> 1450, 1120, 2450, 2380, 980, 1430, 910, 3580, 2400,…
    ## $ polystyrene        <dbl> 1820, 1030, 3100, 2730, 870, 2140, 1090, 4310, 2790…
    ## $ cigarette_butts    <dbl> 126000, 91000, 105000, 100000, 120000, 90000, 56000…
    ## $ glass_bottles      <dbl> 72, 42, 50, 52, 72, 46, 32, 58, 49, 75, 38, 45, 58,…
    ## $ plastic_bags       <dbl> 584, 496, 1080, 896, 368, 672, 416, 1552, 984, 448,…
    ## $ wrappers           <dbl> 1162, 874, 2032, 1971, 753, 1144, 692, 3015, 1988, …
    ## $ sports_balls       <int> 7, 5, 6, 6, 7, 5, 3, 6, 6, 7, 6, 8, 6, 6, 6, 6, 5, …
    ## $ homes_powered      <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
    ## $ trash_wheel        <chr> "Mr. Trash Wheel", "Mr. Trash Wheel", "Mr. Trash Wh…

``` r
head(all_trashwheels)
```

    ## # A tibble: 6 × 15
    ##   dumpster month  year date                weight_tons volume_cubic_yards
    ##      <dbl> <chr> <int> <dttm>                    <dbl>              <dbl>
    ## 1        1 May    2014 2014-05-16 00:00:00        4.31                 18
    ## 2        2 May    2014 2014-05-16 00:00:00        2.74                 13
    ## 3        3 May    2014 2014-05-16 00:00:00        3.45                 15
    ## 4        4 May    2014 2014-05-17 00:00:00        3.1                  15
    ## 5        5 May    2014 2014-05-17 00:00:00        4.06                 18
    ## 6        6 May    2014 2014-05-20 00:00:00        2.71                 13
    ## # ℹ 9 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <int>, homes_powered <dbl>, trash_wheel <chr>

Final answer to the Problem 2.

# To get number of observations from Mr. Trash Wheel, Professor Trash Wheel, and Gwynnda this can be ran:

``` r
num_obs = nrow(all_trashwheels)
```

The key variables are: weight_tons, cigarette_butts, and homes_powered

# Total weight of trash collected by Professor Trash Wheel

``` r
total_weight_prof = professor_trashwheel %>% 
  pull(weight_tons) %>% 
  sum(na.rm = TRUE)
```

# Total cigarette butts for Gwynnda in June 2022:

``` r
total_cigs_gwynnda_june22 = gwynnda %>% 
  filter(year == 2022, month == "June") %>% 
  pull(cigarette_butts) %>% 
  sum(na.rm = TRUE)
```

## Problem 3.

``` r
zori = read_csv("/Users/karolinawiesiolek/Desktop/Data_Science/Homeworks/Homework2/data/Zip_zori_uc_sfrcondomfr_sm_month_NYC.csv") %>% 
  janitor::clean_names()
```

    ## Rows: 149 Columns: 125
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr   (6): RegionType, StateName, State, City, Metro, CountyName
    ## dbl (119): RegionID, SizeRank, RegionName, 2015-01-31, 2015-02-28, 2015-03-3...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
nyc_zip_neighborhood = read_csv("/Users/karolinawiesiolek/Desktop/Data_Science/Homeworks/Homework2/data/Zip Codes.csv") %>%
  janitor::clean_names()
```

    ## Rows: 322 Columns: 7
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (4): County, County Code, File Date, Neighborhood
    ## dbl (3): State FIPS, County FIPS, ZipCode
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Tidying data:

``` r
zori_long = zori %>%
  pivot_longer(
    cols = x2015_01_31:x2024_08_31,
    names_to = "date",
    values_to = "value"
) %>%
  mutate(
    date = str_remove(date, "^x"),              
    date = as.Date(date, format = "%Y_%m_%d"),
    zip_code = str_pad(as.character(region_name), 5, pad = "0")
  )
```

``` r
names(nyc_zip_neighborhood)
```

    ## [1] "county"       "state_fips"   "county_code"  "county_fips"  "zip_code"    
    ## [6] "file_date"    "neighborhood"

``` r
nyc_zip_neighborhood_clean = nyc_zip_neighborhood %>%
  mutate(
    zip_code = str_pad(as.character(zip_code), 5, side = "left", pad = "0"),
    neighborhood = na_if(neighborhood, "NA"),
    borough = case_when(
      county == "New York"  ~ "Manhattan",
      county == "Kings"     ~ "Brooklyn",
      county == "Queens"    ~ "Queens",
      county == "Bronx"     ~ "Bronx",
      county == "Richmond"  ~ "Staten Island",
      TRUE ~ NA_character_
    )
  )
```

``` r
zori_long = zori_long %>%
  mutate(
    zip_code = str_pad(as.character(region_name), 5, "left", "0")
  )
```

Cleaning data:

``` r
nyc_zip_neighborhood_clean = nyc_zip_neighborhood_clean %>%
  group_by(zip_code) %>%
  summarise(
    county = first(na.omit(county)),
    neighborhood = first(na.omit(neighborhood)),
    borough = first(na.omit(borough)),
    .groups = "drop"
  )
```

Joining data together:

``` r
zori_final = zori_long %>%
  left_join(nyc_zip_neighborhood_clean, by = "zip_code")
```

What is in crosswalk but not in Zillow:

``` r
zips_missing=  nyc_zip_neighborhood_clean %>%
  filter(!zip_code %in% zori_final$zip_code)

head(zips_missing %>% select(zip_code, borough, neighborhood), 20)
```

    ## # A tibble: 20 × 3
    ##    zip_code borough   neighborhood       
    ##    <chr>    <chr>     <chr>              
    ##  1 10008    Manhattan <NA>               
    ##  2 10020    Manhattan Chelsea and Clinton
    ##  3 10041    Manhattan <NA>               
    ##  4 10043    Manhattan <NA>               
    ##  5 10045    Manhattan <NA>               
    ##  6 10047    Manhattan <NA>               
    ##  7 10048    Manhattan <NA>               
    ##  8 10055    Manhattan <NA>               
    ##  9 10072    Manhattan <NA>               
    ## 10 10080    Manhattan <NA>               
    ## 11 10081    Manhattan <NA>               
    ## 12 10082    Manhattan <NA>               
    ## 13 10087    Manhattan <NA>               
    ## 14 10101    Manhattan <NA>               
    ## 15 10102    Manhattan <NA>               
    ## 16 10103    Manhattan <NA>               
    ## 17 10104    Manhattan <NA>               
    ## 18 10105    Manhattan <NA>               
    ## 19 10106    Manhattan <NA>               
    ## 20 10107    Manhattan <NA>

``` r
n_obs = nrow(zori_final)
n_zip = n_distinct(zori_final$zip_code)
n_neighborhood <- n_distinct(zori_final$neighborhood, na.rm = TRUE)

cat("Total observations:", n_obs, "\n")
```

    ## Total observations: 17284

``` r
cat("Unique ZIP codes:", n_zip, "\n")
```

    ## Unique ZIP codes: 149

``` r
cat("Unique neighborhoods:", n_neighborhood, "\n")
```

    ## Unique neighborhoods: 42

Data description:

``` r
n_obs = nrow(zori_final)


n_zip = n_distinct(zori_final$zip_code)


n_hoods = n_distinct(na.omit(zori_final$neighborhood))

n_obs; n_zip; n_hoods
```

    ## [1] 17284

    ## [1] 149

    ## [1] 42

Zillow doesn’t track these zip codes and it could be because these are
businesses, PO boxes…

``` r
missing_zips = nyc_zip_neighborhood_clean %>%
  anti_join(zori_final, by = "zip_code")

missing_zips %>% distinct(zip_code, borough, neighborhood)
```

    ## # A tibble: 171 × 3
    ##    zip_code borough   neighborhood       
    ##    <chr>    <chr>     <chr>              
    ##  1 10008    Manhattan <NA>               
    ##  2 10020    Manhattan Chelsea and Clinton
    ##  3 10041    Manhattan <NA>               
    ##  4 10043    Manhattan <NA>               
    ##  5 10045    Manhattan <NA>               
    ##  6 10047    Manhattan <NA>               
    ##  7 10048    Manhattan <NA>               
    ##  8 10055    Manhattan <NA>               
    ##  9 10072    Manhattan <NA>               
    ## 10 10080    Manhattan <NA>               
    ## # ℹ 161 more rows

``` r
zori_final = zori_final %>%
  select(
    zip_code, borough, neighborhood, county,
    region_id, size_rank, city, state, metro,
    date, value
  )
```

I cannot do the portion of the assignment regarding COVID data… I will
leave the code in – but it means that I can knit.

The final tidy dataset merges Zillow rental data with NYC ZIP
code–neighborhood crosswalks. It contains: total observations unique ZIP
codes unique neighborhoods

Some ZIP codes like 10020, 10045, 10080 appear in the crosswalk but not
in Zillow’s dataset. These are for example business districts, PO boxes,
or non-residential areas, which explains their absence from rental data.

During the COVID-19 pandemic, rents fell sharply. The table of the top
10 ZIP codes with the largest drops between Jan 2020 and Jan 2021 shows
that Manhattan neighborhoods were hit hardest.
